"""Render a flat, import-free dispatch_registry.py for Lambda packaging.

`pmf_engine.control_plane.dispatch_registry` imports EXPERIMENT_REGISTRY from
the full registry — fine at source but drags every experiment module (and
instruction markdown) into the Lambda zip. This generator evaluates the
source-tree DISPATCH_REGISTRY once and emits a static copy with no imports,
which the Lambda build pipeline copies into `.lambda_build/`.

Usage:
    python3 -m pmf_engine.scripts.generate_flat_dispatch_registry <output_path>
"""

from __future__ import annotations

import sys
from pathlib import Path


_HEADER = (
    "# Auto-generated by pmf_engine.scripts.generate_flat_dispatch_registry.\n"
    "# DO NOT hand-edit. Source of truth: pmf_engine.control_plane.registry.EXPERIMENT_REGISTRY\n"
    "from __future__ import annotations\n"
    "\n"
)


def render_flat_registry(registry: dict[str, dict]) -> str:
    lines: list[str] = [_HEADER.rstrip("\n"), "", "DISPATCH_REGISTRY: dict[str, dict] = {"]
    for name in sorted(registry.keys()):
        entry = registry[name]
        lines.append(f"    {name!r}: {{")
        lines.append(f'        "harness": {entry["harness"]!r},')
        lines.append(f'        "model": {entry["model"]!r},')
        lines.append(f'        "timeout_seconds": {entry["timeout_seconds"]!r},')
        lines.append(
            f'        "contract": {{"s3_key_template": {entry["contract"]["s3_key_template"]!r}}},'
        )
        lines.append("    },")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main(output_path: Path) -> None:
    from pmf_engine.control_plane.dispatch_registry import DISPATCH_REGISTRY

    output_path.write_text(render_flat_registry(DISPATCH_REGISTRY))
    print(f"Wrote flat DISPATCH_REGISTRY with {len(DISPATCH_REGISTRY)} experiments to {output_path}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(
            "Usage: python3 -m pmf_engine.scripts.generate_flat_dispatch_registry <output_path>",
            file=sys.stderr,
        )
        sys.exit(1)
    main(Path(sys.argv[1]))
