import { createZodDto } from 'nestjs-zod'
import { z } from 'zod'

export const UpdateContactsSegmentSchema = z
  .object({
    name: z.string().optional(),
    genderMale: z.boolean().optional(),
    genderFemale: z.boolean().optional(),
    genderUnknown: z.boolean().optional(),
    age18_25: z.boolean().optional(),
    age25_35: z.boolean().optional(),
    age35_50: z.boolean().optional(),
    age50Plus: z.boolean().optional(),
    politicalPartyDemocrat: z.boolean().optional(),
    politicalPartyNonPartisan: z.boolean().optional(),
    politicalPartyRepublican: z.boolean().optional(),
    address: z.boolean().optional(),
    cellPhone: z.boolean().optional(),
    landline: z.boolean().optional(),
    email: z.boolean().optional(),
    emailNotListed: z.boolean().optional(),
    hasAddress: z.boolean().optional(),
    addressNotListed: z.boolean().optional(),
    hasCellPhone: z.boolean().optional(),
    cellPhoneNotListed: z.boolean().optional(),
    hasLandline: z.boolean().optional(),
    landlineNotListed: z.boolean().optional(),
    hasEmail: z.boolean().optional(),
    registeredVoter: z.boolean().optional(),
    registeredVoterYes: z.boolean().optional(),
    registeredVoterNo: z.boolean().optional(),
    activeVoterYes: z.boolean().optional(),
    activeVoterNo: z.boolean().optional(),
    voterLikelyFirstTime: z.boolean().optional(),
    voterLikelyLikely: z.boolean().optional(),
    voterLikelySuper: z.boolean().optional(),
    voterLikelyUnknown: z.boolean().optional(),
    maritalStatusMarried: z.boolean().optional(),
    maritalStatusLikelyMarried: z.boolean().optional(),
    maritalStatusSingle: z.boolean().optional(),
    maritalStatusLikelySingle: z.boolean().optional(),
    maritalStatusUnknown: z.boolean().optional(),
    hasChildrenNo: z.boolean().optional(),
    hasChildrenYes: z.boolean().optional(),
    hasChildrenUnknown: z.boolean().optional(),
    veteranStatusYes: z.boolean().optional(),
    veteranStatusNo: z.boolean().optional(),
    veteranStatusUnknown: z.boolean().optional(),
    businessOwnerYes: z.boolean().optional(),
    businessOwnerLikely: z.boolean().optional(),
    businessOwnerNo: z.boolean().optional(),
    businessOwnerUnknown: z.boolean().optional(),
    educationHighSchool: z.boolean().optional(),
    educationSomeCollege: z.boolean().optional(),
    educationTechnicalSchool: z.boolean().optional(),
    educationSomeCollegeDegree: z.boolean().optional(),
    educationCollegeDegree: z.boolean().optional(),
    educationGraduateDegree: z.boolean().optional(),
    educationUnknown: z.boolean().optional(),
    householdIncome15_25k: z.boolean().optional(),
    householdIncome25_35k: z.boolean().optional(),
    householdIncome35_50k: z.boolean().optional(),
    householdIncome50_75k: z.boolean().optional(),
    householdIncome75_100k: z.boolean().optional(),
    householdIncome100_125k: z.boolean().optional(),
    householdIncome125_150k: z.boolean().optional(),
    householdIncome150_175k: z.boolean().optional(),
    householdIncome175_200k: z.boolean().optional(),
    householdIncome200_250k: z.boolean().optional(),
    householdIncome250kPlus: z.boolean().optional(),
    householdIncomeUnknown: z.boolean().optional(),
    languageEnglish: z.boolean().optional(),
    languageSpanish: z.boolean().optional(),
    languageOther: z.boolean().optional(),
    ethnicityCaucasian: z.boolean().optional(),
    ethnicityAfricanAmerican: z.boolean().optional(),
    ethnicityAsian: z.boolean().optional(),
    ethnicityEuropean: z.boolean().optional(),
    ethnicityHispanic: z.boolean().optional(),
    ethnicityUnknown: z.boolean().optional(),
  })
  .strict()

export class UpdateContactsSegmentDto extends createZodDto(
  UpdateContactsSegmentSchema,
) {}
