// The row shape of the Databricks voter mart (`mart_gp_api`), hand-maintained.
//
// Prisma generated these types from a people-db Postgres schema until people-db
// was retired. Nothing queries that database any more, but the column names and
// their nullability are still the contract `voter.select.ts`, the CSV download
// list and `transformToPersonOutput` are checked against, so the shape outlived
// the database it was derived from. A column added to or renamed in the mart
// has to be mirrored here, or nothing will know about it.

export type USState =
  | 'AL'
  | 'AK'
  | 'AZ'
  | 'AR'
  | 'CA'
  | 'CO'
  | 'CT'
  | 'DC'
  | 'DE'
  | 'FL'
  | 'GA'
  | 'HI'
  | 'ID'
  | 'IL'
  | 'IN'
  | 'IA'
  | 'KS'
  | 'KY'
  | 'LA'
  | 'ME'
  | 'MD'
  | 'MA'
  | 'MI'
  | 'MN'
  | 'MS'
  | 'MO'
  | 'MT'
  | 'NE'
  | 'NV'
  | 'NH'
  | 'NJ'
  | 'NM'
  | 'NY'
  | 'NC'
  | 'ND'
  | 'OH'
  | 'OK'
  | 'OR'
  | 'PA'
  | 'RI'
  | 'SC'
  | 'SD'
  | 'TN'
  | 'TX'
  | 'UT'
  | 'VT'
  | 'VA'
  | 'WA'
  | 'WV'
  | 'WI'
  | 'WY'

export interface Voter {
  // Core Voter Information
  id: string
  createdAt: Date
  updatedAt: Date
  LALVOTERID: string // Permanent and unique ID generated by L2 for a single voter
  State: USState // Two-letter state code for unified table partitioning
  AbsenteeTypes_Description: string | null // Military, Long Term, In State, Out of State, Permanent Out of Country, Mail Precinct, Special, Temporary, Permanent U.S., Federal
  Active: string | null
  Age: string | null // Age is based on current year minus year of birth.
  Age_Int: number | null
  FirstName: string | null
  MiddleName: string | null // Sometimes represented by just a middle initial.
  LastName: string | null
  Gender: string | null // "M", "F" or blank.

  // Demographics
  Business_Owner: string | null
  CalculatedRegDate: Date | null // format 99/99/9999'; calculated reg date will be the same as official reg date except in those cases where the county has used it as a record update field in which case the calculated registration date will be set to 30 days prior to the oldest recorded vote date as a better indicator of the true registration date of the voter'
  CountyEthnic_Description: string | null
  CountyEthnic_LALEthnicCode: string | null
  CountyVoterID: string | null // If available
  Education_Of_Person: string | null
  Estimated_Income_Amount: string | null
  Estimated_Income_Amount_Int: number | null // Numeric version for range queries and comparisons
  EthnicGroups_EthnicGroup1Desc: string | null
  Ethnic_Description: string | null // one of approximately 100 ethnic categories covering about 90% of voters with the remaining voters classifed as unknown'.  See Ethnic tab.'
  Homeowner_Probability_Model: string | null // ConsumerData_Homeowner_Probability_Model: Home Owner, Probable Home Owner, Renter
  Language_Code: string | null
  Mailing_Addresses_AddressLine: string | null
  Mailing_Addresses_ApartmentNum: string | null
  Mailing_Addresses_ApartmentType: string | null
  Mailing_Addresses_CassErrStatCode: string | null
  Mailing_Addresses_CheckDigit: number | null
  Mailing_Addresses_City: string | null
  Mailing_Addresses_Designator: string | null
  Mailing_Addresses_DPBC: string | null
  Mailing_Addresses_ExtraAddressLine: string | null
  Mailing_Addresses_HouseNumber: string | null
  Mailing_Addresses_PrefixDirection: number | null
  Mailing_Addresses_State: string | null
  Mailing_Addresses_StreetName: string | null
  Mailing_Addresses_SuffixDirection: number | null
  Mailing_Addresses_Zip: string | null
  Mailing_Addresses_ZipPlus4: string | null
  Mailing_Families_FamilyID: string | null // Unique alpha-numeric ID starting with an M' for 'Mailing' that is common to all members of a mailing household address but different from all other mailing households.'
  Mailing_HHGender_Description: string | null // Cannot Determine,Female Only Household,Male Only Household,Mixed Gender Household
  Marital_Status: string | null // ConsumerData_Marital_Status: Inferred Married, Inferred Single, Married, Single, Unknown
  MovedFrom_Date: Date | null
  MovedFrom_Party_Description: string | null // Voters_MovedFrom_Party
  MovedFrom_State: string | null
  NameSuffix: string | null // Jr., Sr, etc.
  OfficialRegDate: string | null // As reported by election authority.
  Parties_Description: string | null // Full name of official party. See Parties tab.
  PlaceOfBirth: string | null // Unformatted and non-standardized text field available only in some states.
  Presence_Of_Children: string | null // ConsumerData_Presence_Of_Children_in_HH
  Residence_Addresses_AddressLine: string | null
  Residence_Addresses_ApartmentNum: string | null
  Residence_Addresses_ApartmentType: string | null
  Residence_Addresses_CassErrStatCode: string | null
  Residence_Addresses_CheckDigit: number | null
  Residence_Addresses_City: string | null
  Residence_Addresses_Designator: string | null
  Residence_Addresses_DPBC: string | null
  Residence_Addresses_ExtraAddressLine: string | null
  Residence_Addresses_HouseNumber: string | null
  Residence_Addresses_LatLongAccuracy: string | null
  Residence_Addresses_Latitude: string | null
  Residence_Addresses_Longitude: string | null
  Residence_Addresses_PrefixDirection: number | null
  Residence_Addresses_State: string | null
  Residence_Addresses_StreetName: string | null
  Residence_Addresses_SuffixDirection: number | null
  Residence_Addresses_Zip: string | null
  Residence_Addresses_ZipPlus4: string | null
  Residence_HHParties_Description: string | null // Same as Mailing HH Parties calculation but based on those sharing the same residence address rather than those sharing the same mailing address
  SequenceOddEven: string | null
  SequenceZigZag: string | null
  StateVoterID: string | null // State-supplied voter ID
  Veteran_Status: string | null // ConsumerDataLL_Veteran
  VoterParties_Change_Changed_Party: string | null // Voter changed party affiliation between Dem and Rep
  Voter_Status: string | null // Turnout-propensity bucket (2026 General) from the in-house model probability. One of: Unlikely (<0.25), Unreliable (<0.50), Likely (<0.75), Super (>=0.75), Unknown (no score). See gp-api src/contacts/CLAUDE.md "The Voter_Status propensity vocabulary".
  Voter_Status_UpdatedAt: Date | null
  VoterTelephones_CellConfidenceCode: number | null
  VoterTelephones_CellPhoneFormatted: string | null
  VoterTelephones_LandlineConfidenceCode: number | null
  VoterTelephones_LandlineFormatted: string | null

  // Voter Turnout
  AnyElection_2017: string | null
  AnyElection_2019: string | null
  AnyElection_2021: string | null
  AnyElection_2023: string | null
  AnyElection_2025: string | null
  General_2016: string | null
  General_2018: string | null
  General_2020: string | null
  General_2022: string | null
  General_2024: string | null
  General_2026: string | null
  OtherElection_2016: string | null
  OtherElection_2018: string | null
  OtherElection_2020: string | null
  OtherElection_2022: string | null
  OtherElection_2024: string | null
  OtherElection_2026: string | null
  PresidentialPrimary_2016: string | null
  PresidentialPrimary_2020: string | null
  PresidentialPrimary_2024: string | null
  Primary_2016: string | null
  Primary_2018: string | null
  Primary_2020: string | null
  Primary_2022: string | null
  Primary_2024: string | null
  Primary_2026: string | null
  VotingPerformanceEvenYearGeneral: string | null
  VotingPerformanceEvenYearGeneralAndPrimary: string | null
  VotingPerformanceEvenYearPrimary: string | null
  VotingPerformanceMinorElection: string | null
}
