import * as pulumi from '@pulumi/pulumi'
import * as aws from '@pulumi/aws'

export interface EinDocumentsBucketConfig {
  environment: 'dev' | 'qa' | 'prod'
}

/**
 * Creates the ein-supporting-documents bucket for storing sensitive campaign
 * EIN/filing documents. This bucket is locked down with full public access
 * blocks - all access should be through signed URLs generated by the API.
 *
 * SECURITY: This bucket contains sensitive campaign filing documents.
 * Direct public access is NOT allowed. Use pre-signed URLs for all access.
 */
export function createEinDocumentsBucket({
  environment,
}: EinDocumentsBucketConfig): {
  bucket: aws.s3.BucketV2
  bucketName: pulumi.Output<string>
} {
  // Use same bucket name across environments - this is an existing bucket
  // that we're importing into IaC management
  const bucketName = 'ein-supporting-documents'

  const bucket = new aws.s3.BucketV2('einDocumentsBucket', {
    bucket: bucketName,
    forceDestroy: false,
  })

  // CRITICAL: Enable ALL public access blocks for this sensitive data bucket
  // This ensures no accidental public exposure of campaign filing documents
  new aws.s3.BucketPublicAccessBlock('einDocumentsBucketPublicAccessBlock', {
    bucket: bucket.id,
    blockPublicAcls: true,
    blockPublicPolicy: true,
    ignorePublicAcls: true,
    restrictPublicBuckets: true,
  })

  // Enable versioning for audit trail and accidental deletion protection
  new aws.s3.BucketVersioningV2('einDocumentsBucketVersioning', {
    bucket: bucket.id,
    versioningConfiguration: {
      status: 'Enabled',
    },
  })

  // Enable server-side encryption with AWS-managed keys
  new aws.s3.BucketServerSideEncryptionConfigurationV2(
    'einDocumentsBucketEncryption',
    {
      bucket: bucket.id,
      rules: [
        {
          applyServerSideEncryptionByDefault: {
            sseAlgorithm: 'AES256',
          },
          bucketKeyEnabled: true,
        },
      ],
    },
  )

  // CORS configuration for signed URL uploads from webapp
  // This bucket is shared across all environments, so allow all origins
  new aws.s3.BucketCorsConfigurationV2('einDocumentsBucketCors', {
    bucket: bucket.id,
    corsRules: [
      {
        allowedHeaders: ['*'],
        allowedMethods: ['GET', 'PUT', 'POST'],
        allowedOrigins: [
          'https://goodparty.org',
          'https://dev.goodparty.org',
          'https://qa.goodparty.org',
          'http://localhost:4000',
        ],
        exposeHeaders: ['ETag'],
        maxAgeSeconds: 3000,
      },
    ],
  })

  // Lifecycle rule to transition old versions to cheaper storage
  new aws.s3.BucketLifecycleConfigurationV2('einDocumentsBucketLifecycle', {
    bucket: bucket.id,
    rules: [
      {
        id: 'transition-old-versions',
        status: 'Enabled',
        noncurrentVersionTransitions: [
          {
            noncurrentDays: 30,
            storageClass: 'STANDARD_IA',
          },
          {
            noncurrentDays: 90,
            storageClass: 'GLACIER',
          },
        ],
        noncurrentVersionExpiration: {
          noncurrentDays: 365,
        },
      },
    ],
  })

  return {
    bucket,
    bucketName: bucket.bucket,
  }
}
