import { z } from 'zod'

/**
 * Base schema containing all voter filter fields used across different contexts
 * (VoterFileFilter creation, P2P phone lists, etc.)
 */
export const voterFilterBaseSchema = z.object({
  audienceSuperVoters: z.boolean().optional(),
  audienceLikelyVoters: z.boolean().optional(),
  audienceUnreliableVoters: z.boolean().optional(),
  audienceUnlikelyVoters: z.boolean().optional(),
  audienceFirstTimeVoters: z.boolean().optional(),
  audienceUnknown: z.boolean().optional(),
  partyIndependent: z.boolean().optional(),
  partyDemocrat: z.boolean().optional(),
  partyRepublican: z.boolean().optional(),
  partyUnknown: z.boolean().optional(),
  age18_25: z.boolean().optional(),
  age25_35: z.boolean().optional(),
  age35_50: z.boolean().optional(),
  age50Plus: z.boolean().optional(),
  ageUnknown: z.boolean().optional(),
  genderMale: z.boolean().optional(),
  genderFemale: z.boolean().optional(),
  genderUnknown: z.boolean().optional(),
  hasCellPhone: z.boolean().optional(),
  hasLandline: z.boolean().optional(),
  // New boolean flags to allow FE to pass simple true/false values
  registeredVoterTrue: z.boolean().optional(),
  registeredVoterFalse: z.boolean().optional(),
  likelyMarried: z.boolean().optional(),
  likelySingle: z.boolean().optional(),
  married: z.boolean().optional(),
  single: z.boolean().optional(),
  maritalUnknown: z.boolean().optional(),
  hasChildrenYes: z.boolean().optional(),
  hasChildrenNo: z.boolean().optional(),
  hasChildrenUnknown: z.boolean().optional(),
  veteranYes: z.boolean().optional(),
  veteranUnknown: z.boolean().optional(),
  homeownerYes: z.boolean().optional(),
  homeownerLikely: z.boolean().optional(),
  homeownerNo: z.boolean().optional(),
  homeownerUnknown: z.boolean().optional(),
  businessOwnerYes: z.boolean().optional(),
  businessOwnerUnknown: z.boolean().optional(),
  educationNone: z.boolean().optional(),
  educationHighSchoolDiploma: z.boolean().optional(),
  educationTechnicalSchool: z.boolean().optional(),
  educationSomeCollege: z.boolean().optional(),
  educationCollegeDegree: z.boolean().optional(),
  educationGraduateDegree: z.boolean().optional(),
  educationUnknown: z.boolean().optional(),
  ethnicityAsian: z.boolean().optional(),
  ethnicityEuropean: z.boolean().optional(),
  ethnicityHispanic: z.boolean().optional(),
  ethnicityAfricanAmerican: z.boolean().optional(),
  ethnicityOther: z.boolean().optional(),
  ethnicityUnknown: z.boolean().optional(),
  languageCodes: z.array(z.string()).optional(),
  voterStatus: z.array(z.string()).optional(),
  incomeRanges: z.array(z.string()).optional(),
})
