"""Render and upsert the consumer-facing event-state surface as a ClickUp doc page
(DATA-2052, sub-ticket B). Consumes event_state_assembler rows; writes via the ClickUp v3
Docs API through clickup_api.py so the same path is automatable later (sub-ticket D)."""

from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import date
from pathlib import Path
from typing import Any

import clickup_api
import event_state_assembler as esa

HERE = Path(__file__).resolve().parent
DATA_DIR = HERE / "instrumentation_data"
DOC_STATE = DATA_DIR / "event_state_doc_state.json"

# The existing ClickUp doc this surface adds a page to (see design doc / ticket).
DEFAULT_DOC_ID = "2ky4jq2q-99953"
PAGE_NAME = "Analytics event state"

_LEGEND = [
    ("active", "code present, fired in the last 30 days"),
    ("dormant", "code present, quiet 30 days — still intended?"),
    ("deprecating", "code removed, within the 30-day holding window"),
    ("orphaned_firing", "code removed but events still arrive — escalate"),
    ("retired", "code removed, quiet 30 days+"),
    ("code_unknown", "no provenance row (auto-tracked or brand-new)"),
    ("instrumented_never_observed", "in code, never seen — possible broken instrumentation"),
    ("system", "auto-tracked (page, [Amplitude] …); never status-flagged"),
]


def _cell(value: Any) -> str:
    return str("" if value is None else value).replace("|", "\\|").replace("\n", " ")


def render_markdown(rows: list[dict], meta: dict) -> str:
    lines = [
        "# Analytics event state",
        "",
        "What every Amplitude event is: its firing status, what replaced it, recent volume, "
        "and where it was instrumented or retired in code. Use it to tell what to trust "
        "without cross-checking Amplitude and git.",
        "",
        f"_Refreshed {meta['refreshed_at']} — {meta['event_count']} events. "
        f"Sources: int__amplitude_event_catalog, {Path(meta['provenance_path']).name}, "
        "analytics_event_health SOP status._",
        "",
        "Generated by the `instrument-analytics-event` and `event-metadata` skills plus the "
        "analytics-event-health monitor. To refresh, see "
        "`books/refresh-event-state-surface.md`.",
        "",
        "## Status legend",
        "",
    ]
    lines += [f"- **{name}** — {meaning}" for name, meaning in _LEGEND]
    lines += [
        "",
        "## Events",
        "",
        "| " + " | ".join(esa.COLUMNS) + " |",
        "| " + " | ".join("---" for _ in esa.COLUMNS) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(_cell(row.get(c)) for c in esa.COLUMNS) + " |")
    return "\n".join(lines) + "\n"
