-- AlterTable
ALTER TABLE "user" ALTER COLUMN "first_name" DROP NOT NULL,
ALTER COLUMN "first_name" SET DEFAULT '',
ALTER COLUMN "last_name" DROP NOT NULL,
ALTER COLUMN "last_name" SET DEFAULT '',
ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "phone" DROP NOT NULL;
