-- CreateTable
CREATE TABLE "contacts_segment" (
    "id" SERIAL NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "name" TEXT NOT NULL,
    "gender_male" BOOLEAN NOT NULL DEFAULT false,
    "gender_female" BOOLEAN NOT NULL DEFAULT false,
    "gender_unknown" BOOLEAN NOT NULL DEFAULT false,
    "age_18_25" BOOLEAN NOT NULL DEFAULT false,
    "age_25_35" BOOLEAN NOT NULL DEFAULT false,
    "age_35_50" BOOLEAN NOT NULL DEFAULT false,
    "age_50_plus" BOOLEAN NOT NULL DEFAULT false,
    "political_party_democrat" BOOLEAN NOT NULL DEFAULT false,
    "political_party_non_partisan" BOOLEAN NOT NULL DEFAULT false,
    "political_party_republican" BOOLEAN NOT NULL DEFAULT false,
    "address" BOOLEAN NOT NULL DEFAULT false,
    "cell_phone" BOOLEAN NOT NULL DEFAULT false,
    "landline" BOOLEAN NOT NULL DEFAULT false,
    "email" BOOLEAN NOT NULL DEFAULT false,
    "email_not_listed" BOOLEAN NOT NULL DEFAULT false,
    "has_address" BOOLEAN NOT NULL DEFAULT false,
    "address_not_listed" BOOLEAN NOT NULL DEFAULT false,
    "has_cell_phone" BOOLEAN NOT NULL DEFAULT false,
    "cell_phone_not_listed" BOOLEAN NOT NULL DEFAULT false,
    "has_landline" BOOLEAN NOT NULL DEFAULT false,
    "landline_not_listed" BOOLEAN NOT NULL DEFAULT false,
    "has_email" BOOLEAN NOT NULL DEFAULT false,
    "registered_voter" BOOLEAN NOT NULL DEFAULT false,
    "registered_voter_yes" BOOLEAN NOT NULL DEFAULT false,
    "registered_voter_no" BOOLEAN NOT NULL DEFAULT false,
    "active_voter_yes" BOOLEAN NOT NULL DEFAULT false,
    "active_voter_no" BOOLEAN NOT NULL DEFAULT false,
    "voter_likely_first_time" BOOLEAN NOT NULL DEFAULT false,
    "voter_likely_likely" BOOLEAN NOT NULL DEFAULT false,
    "voter_likely_super" BOOLEAN NOT NULL DEFAULT false,
    "voter_likely_unknown" BOOLEAN NOT NULL DEFAULT false,
    "marital_status_married" BOOLEAN NOT NULL DEFAULT false,
    "marital_status_likely_married" BOOLEAN NOT NULL DEFAULT false,
    "marital_status_single" BOOLEAN NOT NULL DEFAULT false,
    "marital_status_likely_single" BOOLEAN NOT NULL DEFAULT false,
    "marital_status_unknown" BOOLEAN NOT NULL DEFAULT false,
    "has_children_no" BOOLEAN NOT NULL DEFAULT false,
    "has_children_yes" BOOLEAN NOT NULL DEFAULT false,
    "has_children_unknown" BOOLEAN NOT NULL DEFAULT false,
    "veteran_status_yes" BOOLEAN NOT NULL DEFAULT false,
    "veteran_status_no" BOOLEAN NOT NULL DEFAULT false,
    "veteran_status_unknown" BOOLEAN NOT NULL DEFAULT false,
    "business_owner_yes" BOOLEAN NOT NULL DEFAULT false,
    "business_owner_likely" BOOLEAN NOT NULL DEFAULT false,
    "business_owner_no" BOOLEAN NOT NULL DEFAULT false,
    "business_owner_unknown" BOOLEAN NOT NULL DEFAULT false,
    "education_high_school" BOOLEAN NOT NULL DEFAULT false,
    "education_some_college" BOOLEAN NOT NULL DEFAULT false,
    "education_technical_school" BOOLEAN NOT NULL DEFAULT false,
    "education_some_college_degree" BOOLEAN NOT NULL DEFAULT false,
    "education_college_degree" BOOLEAN NOT NULL DEFAULT false,
    "education_graduate_degree" BOOLEAN NOT NULL DEFAULT false,
    "education_unknown" BOOLEAN NOT NULL DEFAULT false,
    "household_income_15_25k" BOOLEAN NOT NULL DEFAULT false,
    "household_income_25_35k" BOOLEAN NOT NULL DEFAULT false,
    "household_income_35_50k" BOOLEAN NOT NULL DEFAULT false,
    "household_income_50_75k" BOOLEAN NOT NULL DEFAULT false,
    "household_income_75_100k" BOOLEAN NOT NULL DEFAULT false,
    "household_income_100_125k" BOOLEAN NOT NULL DEFAULT false,
    "household_income_125_150k" BOOLEAN NOT NULL DEFAULT false,
    "household_income_150_175k" BOOLEAN NOT NULL DEFAULT false,
    "household_income_175_200k" BOOLEAN NOT NULL DEFAULT false,
    "household_income_200_250k" BOOLEAN NOT NULL DEFAULT false,
    "household_income_250k_plus" BOOLEAN NOT NULL DEFAULT false,
    "household_income_unknown" BOOLEAN NOT NULL DEFAULT false,
    "language_english" BOOLEAN NOT NULL DEFAULT false,
    "language_spanish" BOOLEAN NOT NULL DEFAULT false,
    "language_other" BOOLEAN NOT NULL DEFAULT false,
    "ethnicity_caucasian" BOOLEAN NOT NULL DEFAULT false,
    "ethnicity_african_american" BOOLEAN NOT NULL DEFAULT false,
    "ethnicity_asian" BOOLEAN NOT NULL DEFAULT false,
    "ethnicity_european" BOOLEAN NOT NULL DEFAULT false,
    "ethnicity_hispanic" BOOLEAN NOT NULL DEFAULT false,
    "ethnicity_unknown" BOOLEAN NOT NULL DEFAULT false,
    "campaign_id" INTEGER NOT NULL,

    CONSTRAINT "contacts_segment_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "contacts_segment_campaign_id_key" ON "contacts_segment"("campaign_id");

-- CreateIndex
CREATE UNIQUE INDEX "contacts_segment_name_campaign_id_key" ON "contacts_segment"("name", "campaign_id");

-- AddForeignKey
ALTER TABLE "contacts_segment" ADD CONSTRAINT "contacts_segment_campaign_id_fkey" FOREIGN KEY ("campaign_id") REFERENCES "campaign"("id") ON DELETE CASCADE ON UPDATE CASCADE;
