import type { CampaignTaskDefinition } from './CampaignTaskCatalog.schema'

// Hand-authored task catalog, transcribed from campaign-tasks-master.xlsx
// (58 tasks). This is the closed list: gp-api materializes the static rows,
// the tracker CAP experiment uses the dynamic subset as its menu, and gp-webapp
// renders against it. Keep this file dumb data.
//
// The 9 progress milestones from the sheet are intentionally NOT here; they
// belong to the gamified thermometer, not the task cards.

export const CAMPAIGN_TASK_CATALOG: CampaignTaskDefinition[] = [
  // ----- Pre-launch -----
  {
    id: 'begin-ballot-access',
    phase: 'preLaunch',
    type: 'static',
    category: 'Ballot access',
    title: 'Begin Ballot Access Period',
    description:
      'The date you can start collecting signatures to get on the ballot.',
    channel: 'awareness',
    timing: { kind: 'jurisdiction', pill: 'ballotAccessStart' },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'content-pill',
    pills: ['ballotAccessStart'],
    priorityTier: 'P1',
  },
  {
    id: 'submit-ballot-access-signatures',
    phase: 'preLaunch',
    type: 'static',
    category: 'Ballot access',
    title: 'Submit your Ballot Access Signatures',
    description:
      'Turn in your valid signatures to secure your place on the ballot.',
    channel: 'general',
    timing: { kind: 'jurisdiction', pill: 'filingDeadline' },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'content-pill',
    pills: ['filingDeadline', 'filingFee'],
    priorityTier: 'P1',
  },
  {
    id: 'add-finance-deadlines',
    phase: 'preLaunch',
    type: 'static',
    category: 'Compliance & Admin',
    title: 'Add your campaign finance deadlines to your calendar',
    description:
      'Most campaigns have legal deadlines for finance reports. Add them now so you never miss one.',
    channel: 'awareness',
    timing: { kind: 'onboardingWeek' },
    dayOfWeek: 'saturday',
    electionType: 'both',
    proRequired: false,
    status: 'live',
    personalization: 'content-pill',
    pills: ['financeDeadlines'],
    priorityTier: 'P1',
  },
  {
    id: 'get-meta-verified',
    phase: 'preLaunch',
    type: 'static',
    category: 'Preparation',
    title: 'Get Meta verified',
    description:
      'Get identity verified on Meta so you can run ads on Facebook and Instagram.',
    channel: 'awareness',
    timing: { kind: 'asap' },
    dayOfWeek: 'wednesday',
    electionType: 'both',
    proRequired: false,
    status: 'live',
    personalization: 'static',
    pills: [],
    priorityTier: 'P4',
  },
  {
    id: 'design-materials',
    phase: 'preLaunch',
    type: 'static',
    category: 'Preparation',
    title: 'Design materials',
    description:
      'Design yard signs, door hangers, palm cards, and other materials.',
    channel: 'awareness',
    timing: { kind: 'asap' },
    dayOfWeek: 'thursday',
    electionType: 'both',
    proRequired: false,
    status: 'live',
    personalization: 'content-pill',
    pills: ['candidateName', 'office'],
    priorityTier: 'P4',
  },
  {
    id: 'get-ein',
    phase: 'preLaunch',
    type: 'static',
    category: 'Setup',
    title: 'Get your EIN',
    description:
      "Your campaign needs its own federal tax ID before you can open a bank account. Apply free on the IRS website with Form SS-4 and mark line 9B 'political organization.'",
    channel: 'general',
    timing: { kind: 'asap' },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'static',
    pills: [],
    priorityTier: 'P1',
  },
  {
    id: 'open-bank-account',
    phase: 'preLaunch',
    type: 'static',
    category: 'Setup',
    title: 'Open a campaign bank account',
    description:
      "Open a bank account in your committee's name using your new EIN. Never run campaign money through your personal account.",
    channel: 'general',
    timing: { kind: 'asap' },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'static',
    pills: [],
    priorityTier: 'P1',
    unlocksAfter: 'Get your EIN',
  },
  {
    id: 'register-with-state',
    phase: 'preLaunch',
    type: 'static',
    category: 'Setup',
    title: 'Register with your state',
    description:
      "Officially register your campaign committee with your state's campaign finance agency and pay any filing fee so you're cleared to raise and spend money.",
    channel: 'general',
    timing: { kind: 'jurisdiction' },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'content-pill',
    pills: ['state', 'filingAgency', 'filingFee'],
    priorityTier: 'P1',
  },
  {
    id: 'get-po-box',
    phase: 'preLaunch',
    type: 'static',
    category: 'Setup',
    title: 'Get a campaign PO Box',
    description:
      "Get a PO Box for campaign mail so your home address doesn't become public record.",
    channel: 'general',
    timing: { kind: 'asap' },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'static',
    pills: [],
    priorityTier: 'P4',
  },
  {
    id: 'setup-email-phone',
    phase: 'preLaunch',
    type: 'static',
    category: 'Setup',
    title: 'Set up a campaign email and phone',
    description:
      'Create a campaign-only email and phone number (a free Gmail and Google Voice work great) to keep campaign messages separate from your personal life.',
    channel: 'general',
    timing: { kind: 'asap' },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'static',
    pills: [],
    priorityTier: 'P4',
  },
  {
    id: 'submit-voters-pamphlet',
    phase: 'preLaunch',
    type: 'static',
    category: 'Setup',
    title: "Submit to your local voters' pamphlet",
    description:
      "Many areas publish a voters' pamphlet that is free publicity. Submit your statement before the deadline.",
    channel: 'general',
    timing: { kind: 'jurisdiction', pill: 'pamphletDeadline' },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'content-pill',
    pills: ['pamphletDeadline', 'jurisdiction'],
    priorityTier: 'P3',
  },
  {
    id: 'setup-online-donations',
    phase: 'preLaunch',
    type: 'static',
    category: 'Fundraising',
    title: 'Set up online donations',
    description:
      'Set up a donation page with a nonpartisan processor like Anedot so supporters can give online in a few clicks.',
    channel: 'general',
    timing: { kind: 'preLaunch' },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'static',
    pills: [],
    priorityTier: 'P2',
    unlocksAfter: 'Open a campaign bank account',
  },
  {
    id: 'build-call-list',
    phase: 'preLaunch',
    type: 'static',
    category: 'Fundraising',
    title: 'Build your call list',
    description:
      'Spend a few hours going through your phone, email, LinkedIn, and any groups you belong to, and build a list of 100 to 200 people you can ask for support. This is the single best thing you can do for fundraising.',
    channel: 'general',
    timing: { kind: 'onboardingWeek' },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'content-pill',
    pills: ['fundraisingGoal'],
    priorityTier: 'P2',
  },
  {
    id: 'pick-treasurer',
    phase: 'preLaunch',
    type: 'static',
    category: 'Fundraising',
    title: 'Pick your treasurer',
    description:
      "Choose someone you trust to track your campaign's money and filings, ideally someone other than your spouse.",
    channel: 'general',
    timing: { kind: 'preLaunch' },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'static',
    pills: [],
    priorityTier: 'P4',
  },

  // ----- Launch -----
  {
    id: 'organize-house-party',
    phase: 'launch',
    type: 'static',
    category: 'Events & Volunteer Organizing',
    title: 'Organize a House Party with Supporters',
    description:
      'Work with supporters to host an informal house party where you talk to voters directly.',
    channel: 'general',
    timing: { kind: 'recurring', interval: 'monthly' },
    dayOfWeek: 'wednesday',
    electionType: 'both',
    proRequired: false,
    status: 'live',
    personalization: 'content-pill',
    pills: ['districtName'],
    priorityTier: 'P2',
  },
  {
    id: 'organize-kickoff-fundraiser',
    phase: 'launch',
    type: 'static',
    category: 'Fundraising',
    title: 'Organize a kickoff fundraiser',
    description:
      'Work with supporters to plan a fundraiser to get the financial support you need.',
    channel: 'general',
    timing: { kind: 'recurring', interval: 'monthly' },
    dayOfWeek: 'wednesday',
    electionType: 'both',
    proRequired: false,
    status: 'live',
    personalization: 'content-pill',
    pills: ['fundraisingGoal', 'nextFundraisingMilestone'],
    priorityTier: 'P2',
    unlocksAfter: 'Set up online donations',
  },
  {
    id: 'submit-letters-to-editor',
    phase: 'launch',
    type: 'static',
    category: 'Communications & Visibility',
    title: 'Submit 2 Letters to the Editor',
    description:
      'Have supporters write letters to the editor backing your campaign to the local press.',
    channel: 'general',
    timing: { kind: 'electionRelative', offset: 4, unit: 'weeks' },
    dayOfWeek: 'thursday',
    electionType: 'both',
    proRequired: false,
    status: 'live',
    personalization: 'generated-per-item',
    pills: ['pressOutlet', 'outletContact', 'pitchAngle', 'topIssue'],
    priorityTier: 'P3',
    generatorSource: 'pressOutlets',
  },
  {
    id: 'pick-announcement-date',
    phase: 'launch',
    type: 'static',
    category: 'Launch',
    title: 'Pick your announcement date',
    description:
      "Choose the day you go public. Time it against the election calendar and your opponent's likely announcement, not just when you feel ready.",
    channel: 'general',
    timing: { kind: 'launch' },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'content-pill',
    pills: ['electionDay', 'filingDeadline'],
    priorityTier: 'P2',
  },
  {
    id: 'hold-kickoff-event',
    phase: 'launch',
    type: 'static',
    category: 'Launch',
    title: 'Hold your kickoff event',
    description:
      'Make it official. Gather friends, family, neighbors, and early supporters for a launch event that gives your campaign its first burst of energy and content.',
    channel: 'general',
    timing: { kind: 'launch' },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'content-pill',
    pills: ['districtName', 'candidateSuperpower'],
    priorityTier: 'P2',
  },
  {
    id: 'lock-in-three-messages',
    phase: 'launch',
    type: 'static',
    category: 'Launch',
    title: 'Lock in your three messages',
    description:
      'Write the three short sentences you will repeat everywhere: every door, interview, and event. Saying the same three things all the way to election day is how local races are won.',
    channel: 'general',
    timing: { kind: 'launch' },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'content-pill',
    pills: ['topIssues', 'candidateSuperpower'],
    priorityTier: 'P2',
  },
  {
    id: 'launch-website',
    phase: 'launch',
    type: 'static',
    category: 'Launch',
    title: 'Launch your website',
    description:
      'Put up a simple site with a working donate button, an email signup form, and a page on your top three issues.',
    channel: 'general',
    timing: { kind: 'launch' },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'content-pill',
    pills: ['candidateName', 'office', 'topIssues'],
    priorityTier: 'P2',
  },
  {
    id: 'setup-social-media',
    phase: 'launch',
    type: 'static',
    category: 'Launch',
    title: 'Set up your social media',
    description:
      'Claim your handles on each platform with the same photo and bio everywhere so voters recognize you.',
    channel: 'general',
    timing: { kind: 'launch' },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'content-pill',
    pills: ['candidateName', 'office'],
    priorityTier: 'P2',
  },

  // ----- Active campaign -----
  {
    id: 'knock-on-doors',
    phase: 'active',
    type: 'dynamic',
    category: 'Voter Outreach & Persuasion',
    title: 'Knock on Doors',
    description: 'Knock your target doors to connect with voters face-to-face.',
    channel: 'doorKnocking',
    timing: { kind: 'recurring', interval: 'weekly' },
    dayOfWeek: 'friday',
    electionType: 'both',
    proRequired: true,
    status: 'live',
    personalization: 'content-pill',
    pills: ['contactGoal', 'targetDoors', 'precinct', 'topIssue'],
    priorityTier: 'P2',
  },
  {
    id: 'make-phone-bank-calls',
    phase: 'active',
    type: 'dynamic',
    category: 'Voter Outreach & Persuasion',
    title: 'Make phone bank calls',
    description:
      'Complete a phone bank shift to reach voters and share your message.',
    channel: 'phoneBanking',
    timing: { kind: 'recurring', interval: 'weekly' },
    dayOfWeek: 'friday',
    electionType: 'both',
    proRequired: true,
    status: 'live',
    personalization: 'content-pill',
    pills: ['contactGoal', 'callTarget', 'topIssue'],
    priorityTier: 'P2',
  },
  {
    id: 'schedule-social-posts',
    phase: 'active',
    type: 'dynamic',
    category: 'Communications & Visibility',
    title: 'Plan and Schedule 2 Social Posts for the week',
    description:
      'Plan and schedule two social posts to engage supporters and reach voters.',
    channel: 'general',
    timing: { kind: 'recurring', interval: 'weekly' },
    dayOfWeek: 'friday',
    electionType: 'both',
    proRequired: false,
    status: 'live',
    personalization: 'content-pill',
    pills: ['topIssue', 'recentEvent'],
    priorityTier: 'P3',
  },
  {
    id: 'social-media-update',
    phase: 'active',
    type: 'dynamic',
    category: 'Communications & Visibility',
    title: 'Social media update',
    description:
      'Post campaign activities and photos on your channel of choice.',
    channel: 'general',
    timing: { kind: 'recurring', interval: 'weekly' },
    dayOfWeek: 'friday',
    electionType: 'both',
    proRequired: false,
    status: 'live',
    personalization: 'content-pill',
    pills: ['recentActivity'],
    priorityTier: 'P3',
  },
  {
    id: 'fundraising-ask',
    phase: 'active',
    type: 'dynamic',
    category: 'Fundraising',
    title: 'Fundraising ask',
    description:
      'Make a fundraising solicitation (email and/or social) to close the month strong.',
    channel: 'general',
    timing: { kind: 'recurring', interval: 'weekly' },
    dayOfWeek: 'friday',
    electionType: 'both',
    proRequired: false,
    status: 'live',
    personalization: 'content-pill',
    pills: ['fundraisingGoal', 'amountRaised'],
    priorityTier: 'P2',
    unlocksAfter: 'Set up online donations',
  },
  {
    id: 'email-update',
    phase: 'active',
    type: 'dynamic',
    category: 'Communications & Visibility',
    title: 'Email update',
    description: 'Send a campaign progress update to your email contacts.',
    channel: 'general',
    timing: { kind: 'recurring', interval: 'monthly' },
    dayOfWeek: 'friday',
    electionType: 'both',
    proRequired: false,
    status: 'live',
    personalization: 'content-pill',
    pills: ['recentMilestone'],
    priorityTier: 'P3',
  },
  {
    id: 'organize-volunteer-event',
    phase: 'active',
    type: 'dynamic',
    category: 'Events & Volunteer Organizing',
    title: 'Organize a Volunteer Voter Contact Event',
    description:
      'Give supporters a way to give back. Plan a volunteer voter contact event.',
    channel: 'general',
    timing: { kind: 'recurring', interval: 'evenWeeks' },
    dayOfWeek: 'tuesday',
    electionType: 'both',
    proRequired: false,
    status: 'live',
    personalization: 'content-pill',
    pills: ['contactGoal'],
    priorityTier: 'P2',
  },
  {
    id: 'hold-volunteer-event',
    phase: 'active',
    type: 'dynamic',
    category: 'Events & Volunteer Organizing',
    title: 'Hold a Volunteer Voter Contact Event',
    description:
      'Bring volunteers together to connect with voters and build momentum.',
    channel: 'general',
    timing: { kind: 'recurring', interval: 'oddWeeks' },
    dayOfWeek: 'tuesday',
    electionType: 'both',
    proRequired: false,
    status: 'live',
    personalization: 'content-pill',
    pills: ['contactGoal'],
    priorityTier: 'P2',
    unlocksAfter: 'Organize a Volunteer Voter Contact Event',
  },
  {
    id: 'attend-community-event',
    phase: 'active',
    type: 'dynamic',
    category: 'Events',
    title: 'Attend a community event',
    description:
      "Show up where voters already gather. Your plan's events list creates one card per event - festival, parade, farmers' market, holiday celebration, or candidate forum - each with its own date and address. Sign up or RSVP ahead where the event needs it.",
    channel: 'event',
    timing: { kind: 'perItem' },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'generated-per-item',
    pills: ['eventName', 'eventDate', 'eventAddress', 'eventWhy'],
    priorityTier: 'P3',
    generatorSource: 'communityEvents',
  },
  {
    id: 'attend-related-office-meeting',
    phase: 'active',
    type: 'dynamic',
    category: 'Events',
    title: 'Attend the local related-office meeting',
    description:
      "Attend the public meeting for the office you are running for (e.g. city council). Generated from the governing body's meeting calendar, not the plan's events list.",
    channel: 'event',
    timing: { kind: 'perItem' },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'generated-per-item',
    pills: ['meetingName', 'meetingDate', 'office'],
    priorityTier: 'P3',
    generatorSource: 'officeMeetings',
  },
  {
    id: 'setup-opponent-monitoring',
    phase: 'active',
    type: 'dynamic',
    category: 'Opponent',
    title: 'Set up opponent monitoring',
    description:
      'Set Google Alerts for your opponents and watch local news. Most of the time the right move is not to respond, so decide on purpose rather than reacting to everything.',
    channel: 'general',
    timing: { kind: 'recurring', interval: 'weekly' },
    dayOfWeek: 'monday',
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'content-pill',
    pills: ['opponentName', 'opponentParty', 'isIncumbent'],
    priorityTier: 'P3',
  },
  {
    id: 'send-direct-mail',
    phase: 'active',
    type: 'dynamic',
    category: 'Direct mail',
    title: 'Send a direct mail piece',
    description:
      'Plan a mail program of at least three pieces over the campaign and send your first one. Repetition is what makes mail stick.',
    channel: 'directMail',
    timing: { kind: 'recurring', interval: 'waves' },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'content-pill',
    pills: ['topIssue', 'contactGoal'],
    priorityTier: 'P2',
  },
  {
    id: 'record-voter-contacts',
    phase: 'active',
    type: 'dynamic',
    category: 'Progress & tracking',
    title: 'Record your voter contacts',
    description:
      "Log the doors, calls, and conversations you had off the platform this week so your progress counts everything you've done, not just what ran through GoodParty. Continues every week through GOTV.",
    channel: 'general',
    timing: { kind: 'recurring', interval: 'weekly' },
    dayOfWeek: 'sunday',
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'content-pill',
    pills: ['contactGoal', 'contactsToDate'],
    priorityTier: 'P1',
  },
  {
    id: 'introduction-robocall',
    phase: 'active',
    type: 'dynamic',
    category: 'Voter Outreach & Persuasion',
    title: 'Introduction Robocall',
    description: 'Introduce yourself to voters with an automated call.',
    channel: 'robocall',
    timing: { kind: 'electionRelative', offset: 4, unit: 'weeks' },
    electionType: 'adapts',
    proRequired: true,
    status: 'live',
    personalization: 'content-pill',
    pills: ['candidateName', 'office', 'sendDate'],
    priorityTier: 'P1',
  },
  {
    id: 'introduction-text',
    phase: 'active',
    type: 'dynamic',
    category: 'Voter Outreach & Persuasion',
    title: 'Introduction Text',
    description: 'Introduce yourself to voters with a text.',
    channel: 'text',
    timing: { kind: 'electionRelative', offset: 4, unit: 'weeks' },
    electionType: 'adapts',
    proRequired: true,
    status: 'live',
    personalization: 'content-pill',
    pills: ['candidateName', 'office', 'sendDate'],
    priorityTier: 'P1',
    unlocksAfter: '10DLC registration',
  },
  {
    id: 'persuasion-robocall',
    phase: 'active',
    type: 'dynamic',
    category: 'Voter Outreach & Persuasion',
    title: 'Persuasion Robocall',
    description:
      'Build trust and make your case for why voters should pick you, by automated call.',
    channel: 'robocall',
    timing: { kind: 'electionRelative', offset: 2, unit: 'weeks' },
    electionType: 'adapts',
    proRequired: true,
    status: 'live',
    personalization: 'content-pill',
    pills: ['topIssues', 'opponentName', 'sendDate'],
    priorityTier: 'P1',
  },
  {
    id: 'persuasion-text',
    phase: 'active',
    type: 'dynamic',
    category: 'Voter Outreach & Persuasion',
    title: 'Persuasion Text',
    description: 'Build trust and make your case by text.',
    channel: 'text',
    timing: { kind: 'electionRelative', offset: 2, unit: 'weeks' },
    electionType: 'adapts',
    proRequired: true,
    status: 'live',
    personalization: 'content-pill',
    pills: ['topIssues', 'opponentName', 'sendDate'],
    priorityTier: 'P1',
    unlocksAfter: '10DLC registration',
  },

  // ----- GOTV -----
  {
    id: 'voter-registration-deadline',
    phase: 'gotv',
    type: 'dynamic',
    category: 'Election admin',
    title: 'Voter Registration Deadline',
    description: 'Final day for voters to register for this election.',
    channel: 'awareness',
    timing: { kind: 'jurisdiction', pill: 'regDeadline' },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'content-pill',
    pills: ['regDeadline'],
    priorityTier: 'P1',
  },
  {
    id: 'early-voting-start',
    phase: 'gotv',
    type: 'dynamic',
    category: 'Election admin',
    title: 'Early Voting Start Date',
    description: 'Beginning of the early vote period.',
    channel: 'awareness',
    timing: { kind: 'jurisdiction', pill: 'earlyVotingStart' },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'content-pill',
    pills: ['earlyVotingStart'],
    priorityTier: 'P1',
  },
  {
    id: 'early-voting-end',
    phase: 'gotv',
    type: 'dynamic',
    category: 'Election admin',
    title: 'Early Voting End Date',
    description: 'End of the early vote period.',
    channel: 'awareness',
    timing: { kind: 'jurisdiction', pill: 'earlyVotingEnd' },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'content-pill',
    pills: ['earlyVotingEnd'],
    priorityTier: 'P1',
  },
  {
    id: 'election-day',
    phase: 'gotv',
    type: 'dynamic',
    category: 'Get Out the Vote (GOTV)',
    title: 'Election Day',
    description:
      'Today is Election Day! Get out and vote, and make sure your supporters do too. Good luck!',
    channel: 'awareness',
    timing: { kind: 'electionDay' },
    dayOfWeek: undefined,
    electionType: 'adapts',
    proRequired: false,
    status: 'live',
    personalization: 'content-pill',
    pills: ['electionDay', 'electionType'],
    priorityTier: 'P1',
  },
  {
    id: 'greet-voters-at-polls',
    phase: 'gotv',
    type: 'static',
    category: 'Holidays/parades/external events',
    title: 'Greet voters at the polls',
    description:
      'Your last chance to make an impression. Shake hands and introduce yourself as voters head in.',
    channel: 'event',
    timing: { kind: 'electionDay' },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'content-pill',
    pills: ['electionDay', 'pollingPlaces'],
    priorityTier: 'P2',
  },
  {
    id: 'gotv-social-post',
    phase: 'gotv',
    type: 'dynamic',
    category: 'Communications & Visibility',
    title: 'Create a Get Out The Vote social post',
    description: 'Remind your supporters that it is time to vote.',
    channel: 'general',
    timing: { kind: 'electionDay' },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'content-pill',
    pills: ['electionDay', 'votesNeededToWin'],
    priorityTier: 'P3',
  },
  {
    id: 'early-voting-text',
    phase: 'gotv',
    type: 'dynamic',
    category: 'Voter Outreach & Persuasion',
    title: 'Early Voting Text',
    description: 'Encourage your supporters to vote early.',
    channel: 'text',
    timing: { kind: 'electionRelative', offset: 2, unit: 'weeks' },
    electionType: 'adapts',
    proRequired: true,
    status: 'live',
    personalization: 'content-pill',
    pills: ['sendDate', 'earlyVotingStart', 'earlyVotingEnd'],
    priorityTier: 'P1',
    unlocksAfter: '10DLC registration',
  },
  {
    id: 'election-day-reminder-robocall',
    phase: 'gotv',
    type: 'dynamic',
    category: 'Voter Outreach & Persuasion',
    title: 'Election Day Reminder Robocall',
    description:
      'Get out the vote with an automated call on election (or primary) day.',
    channel: 'robocall',
    timing: { kind: 'electionRelative', offset: 1, unit: 'days' },
    electionType: 'adapts',
    proRequired: true,
    status: 'live',
    personalization: 'content-pill',
    pills: ['sendDate', 'electionDay'],
    priorityTier: 'P1',
  },
  {
    id: 'election-day-reminder-text',
    phase: 'gotv',
    type: 'dynamic',
    category: 'Voter Outreach & Persuasion',
    title: 'Election Day Reminder Text',
    description: 'Get out the vote with a text on election (or primary) day.',
    channel: 'text',
    timing: { kind: 'electionRelative', offset: 1, unit: 'days' },
    electionType: 'adapts',
    proRequired: true,
    status: 'live',
    personalization: 'content-pill',
    pills: ['sendDate', 'electionDay'],
    priorityTier: 'P1',
    unlocksAfter: '10DLC registration',
  },
  {
    id: 'build-chase-list',
    phase: 'gotv',
    type: 'dynamic',
    category: 'Get Out the Vote (GOTV)',
    title: 'Build your chase list',
    description:
      'Pull together the list of supporters who are with you but have not voted yet. These are the people your final push is all about.',
    channel: 'general',
    timing: { kind: 'electionRelative', offset: 3, unit: 'days' },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'content-pill',
    pills: ['identifiedSupporters', 'votesNeededToWin'],
    priorityTier: 'P1',
    unlocksAfter: 'Record your voter contacts',
  },
  {
    id: 'start-vote-tripling',
    phase: 'gotv',
    type: 'dynamic',
    category: 'Get Out the Vote (GOTV)',
    title: 'Start vote tripling',
    description:
      'Ask each supporter to remind three friends to vote, and write down their names. One of the cheapest ways to add votes in the final stretch.',
    channel: 'general',
    timing: { kind: 'electionRelative', offset: 2, unit: 'days' },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'content-pill',
    pills: ['identifiedSupporters'],
    priorityTier: 'P1',
    unlocksAfter: 'Build your chase list',
  },
  {
    id: 'recruit-poll-watchers',
    phase: 'gotv',
    type: 'static',
    category: 'Election day ops',
    title: 'Recruit poll watchers',
    description:
      'Where your state allows it, line up volunteers to watch the polls on election day.',
    channel: 'general',
    timing: { kind: 'electionRelative', offset: 1, unit: 'days' },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'content-pill',
    pills: ['state', 'pollingPlaces'],
    priorityTier: 'P1',
  },
  {
    id: 'organize-rides-to-polls',
    phase: 'gotv',
    type: 'static',
    category: 'Election day ops',
    title: 'Organize rides to the polls',
    description:
      'Set up a simple way to get supporters who need a ride to their polling place.',
    channel: 'general',
    timing: { kind: 'electionRelative', offset: 1, unit: 'days' },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'content-pill',
    pills: ['pollingPlaces'],
    priorityTier: 'P1',
  },
  {
    id: 'track-who-voted',
    phase: 'gotv',
    type: 'static',
    category: 'Election day ops',
    title: 'Track who has voted',
    description:
      'Keep a live list of which supporters have voted so your team knows who still needs a friendly reminder.',
    channel: 'general',
    timing: { kind: 'electionDay' },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'content-pill',
    pills: ['chaseList'],
    priorityTier: 'P1',
    unlocksAfter: 'Build your chase list',
  },
  {
    id: 'thank-volunteers',
    phase: 'gotv',
    type: 'static',
    category: 'Close-out',
    title: 'Thank your volunteers',
    description:
      'Send a personal thank-you to every volunteer who showed up. They are the reason you made it through, win or lose.',
    channel: 'general',
    timing: { kind: 'afterElection', weeks: 1 },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'content-pill',
    pills: ['volunteerList'],
    priorityTier: 'P2',
  },
  {
    id: 'thank-donors',
    phase: 'gotv',
    type: 'static',
    category: 'Close-out',
    title: 'Thank your donors',
    description:
      'Send a thank-you to every person who gave. It keeps them with you for whatever comes next.',
    channel: 'general',
    timing: { kind: 'afterElection', weeks: 1 },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'content-pill',
    pills: ['donorList'],
    priorityTier: 'P2',
  },
  {
    id: 'post-election-message',
    phase: 'gotv',
    type: 'static',
    category: 'Close-out',
    title: 'Share your post-election message',
    description:
      'Win or lose, post a short public statement thanking your supporters and your community.',
    channel: 'general',
    timing: { kind: 'electionDay' },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'content-pill',
    pills: ['result', 'votesNeededToWin'],
    priorityTier: 'P2',
  },
  {
    id: 'file-final-report',
    phase: 'gotv',
    type: 'static',
    category: 'Close-out',
    title: 'File your final report',
    description:
      'Submit your final campaign finance report on time so you close out cleanly.',
    channel: 'general',
    timing: { kind: 'afterElection', weeks: 2 },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'content-pill',
    pills: ['finalFilingDeadline', 'state'],
    priorityTier: 'P1',
  },
  {
    id: 'write-campaign-debrief',
    phase: 'gotv',
    type: 'static',
    category: 'Close-out',
    title: 'Write your campaign debrief',
    description:
      'Note what worked and what did not while it is fresh. If you run again, this is gold.',
    channel: 'general',
    timing: { kind: 'afterElection', weeks: 2 },
    electionType: 'both',
    proRequired: false,
    status: 'proposed',
    personalization: 'content-pill',
    pills: ['campaignStats'],
    priorityTier: 'P2',
  },
]
